services:
    oauth_aware.fos_user_provider:
#        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        class: App\Provider\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - {google: googleId, github: githubId}