httplug:
    plugins:
        redirect:
            preserve_header: true

    discovery:
        client: 'auto'

    clients:
        app:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
#        default:
#            factory: 'httplug.factory.curl'
#        hwi_special:
#            factory: 'httplug.factory.guzzle6'
#            config: # You pass here the Guzzle configuration, exactly like before.
#                timeout: 10
#                verify: false
#                max_redirects: 1
#                ignore_errors: false
#                proxy: "example.com:8080"